@startjson
{
    "name": "Giannis Antetokounmpo",
    "playerId": 3032977,
    "position": "PF",
    "eligibleSlots": [
    "SF",
    "PF",
    "F",
    "SG/SF",
    "G/F",
    "PF/C",
    "F/C",
    "UT",
    "BE",
    "IR"
    ],
    "acquisitionType": [],
    "proTeam": "MIL",
    "injuryStatus": "ACTIVE",
    "stats": {
        "002020": {
            "avg": {
                "PTS": 29.649122807017545,
                "BLK": 1.0175438596491229,
                "STL": 1.0350877192982457,
                "AST": 5.771929824561403,
                "OREB": 2.280701754385965,
                "DREB": 11.456140350877194,
                "REB": 13.736842105263158,
                "PF": 3.0350877192982457,
                "TO": 3.6666666666666665,
                "FGM": 10.929824561403509,
                "FGA": 19.982456140350877,
                "FTM": 6.333333333333333,
                "FTA": 10.0,
                "3PTM": 1.456140350877193,
                "3PTA": 4.754385964912281,
                "FG%": 0.54697103,
                "FT%": 0.63333333,
                "3PT%": 0.30627306,
                "MPG": 30.9122807,
                "MIN": 30.912280701754387,
                "GP": 1.0
            }
            ,
            "total": {
                "PTS": 1690.0,
                "BLK": 58.0,
                "STL": 59.0,
                "AST": 329.0,
                "OREB": 130.0,
                "DREB": 653.0,
                "REB": 783.0,
                "PF": 173.0,
                "TO": 209.0,
                "FGM": 623.0,
                "FGA": 1139.0,
                "FTM": 361.0,
                "FTA": 570.0,
                "3PTM": 83.0,
                "3PTA": 271.0,
                "FG%": 0.54697103,
                "FT%": 0.63333333,
                "3PT%": 0.30627306,
                "MPG": 30.9122807,
                "MIN": 1762.0,
                "GP": 57.0
            }
        }
        ,
        "102021": {
            "avg": {
                "PTS": 29.328358208955223,
                "BLK": 1.2985074626865671,
                "STL": 1.1940298507462686,
                "AST": 5.402985074626866,
                "REB": 13.0,
                "TO": 3.5970149253731343,
                "FGM": 10.686567164179104,
                "FGA": 19.299999999999997,
                "FTM": 6.7164179104477615,
                "FTA": 9.8,
                "3PTM": 1.2388059701492538,
                "3PTA": 3.7,
                "FG%": 0.554,
                "FT%": 0.685,
                "3PT%": 0.334,
                "MPG": 33.3,
                "MIN": 33.3
            }
            ,
            "total": {
                "PTS": 1965.0,
                "BLK": 87.0,
                "STL": 80.0,
                "AST": 362.0,
                "REB": 871.0,
                "TO": 241.0,
                "FGM": 716.0,
                "FGA": 1293.1,
                "FTM": 450.0,
                "FTA": 656.6,
                "3PTM": 83.0,
                "3PTA": 247.9,
                "FG%": 0.554,
                "FT%": 0.685,
                "3PT%": 0.334,
                "MPG": 33.3,
                "MIN": 2231.1
            }
        }
        ,
        "102020": {
            "avg": { "FGM": 10.125, "FTM": 7.1625 },
            "total": {
                "FGM": 810.0, "FTM": 573.0 }
            }
        }
    }

    @endjson
